<?

$smilies = array(
  ":)" => "smile1.gif",
  ";)" => "wink.gif",
  ":D" => "grin.gif",
  ":P" => "tongue.gif",
  ":(" => "sad.gif",
  ":'(" => "cry.gif",
  ":|" => "noexpression.gif",
  ":-/" => "confused.gif",
  ":-O" => "ohmy.gif",
  "8)" => "cool1.gif",
  "O:-" => "angel.gif",
  "-_-" => "sleep.gif",
  ":grrr:" => "angry.gif",
  ":smile:" => "smile2.gif",
  ":lol:" => "laugh.gif",
  ":cool:" => "cool2.gif",
  ":fun:" => "fun.gif",
  ":thumbsup:" => "thumbsup.gif",
  ":thumbsdown:" => "thumbsdown.gif",
  ":blush:" => "blush.gif",
  ":weep:" => "weep.gif",
  ":unsure:" => "unsure.gif",
  ":closedeyes:" => "closedeyes.gif",
  ":yes:" => "yes.gif",
  ":no:" => "no.gif",
  ":love:" => "love.gif",
  ":?:" => "question.gif",
  ":!:" => "excl.gif",
  ":idea:" => "idea.gif",
  ":arrow:" => "arrow.gif",
  ":hmm:" => "hmm.gif",
  ":huh:" => "huh.gif",
  ":w00t:" => "w00t.gif",
  ":geek:" => "geek.gif",
  ":look:" => "look.gif",
  ":rolleyes:" => "rolleyes.gif",
  ":kiss:" => "kiss.gif",
  ":shifty:" => "shifty.gif",
  ":blink:" => "blink.gif",
  ":smartass:" => "smartass.gif",
  ":sick:" => "sick.gif",
  ":crazy:" => "crazy.gif",
  ":wacko:" => "wacko.gif",
  ":alien:" => "alien.gif",
  ":wizard:" => "wizard.gif",
  ":wave:" => "wave.gif",
  ":wavecry:" => "wavecry.gif",
  ":baby:" => "baby.gif",
  ":ras:" => "ras.gif",
  ":sly:" => "sly.gif",
  ":devil:" => "devil.gif",
  ":evil:" => "evil.gif",
  ":evilmad:" => "evilmad.gif",
  ":yucky:" => "yucky.gif",
  ":nugget:" => "nugget.gif",
  ":sneaky:" => "sneaky.gif",
  ":smart:" => "smart.gif",
  ":shutup:" => "shutup.gif",
  ":shutup2:" => "shutup2.gif",
  ":yikes:" => "yikes.gif",
  ":flowers:" => "flowers.gif",
  ":wub:" => "wub.gif",
  ":osama:" => "osama.gif",
  ":saddam:" => "saddam.gif",
  ":santa:" => "santa.gif",
  ":indian:" => "indian.gif",
  ":guns:" => "guns.gif",
  ":crockett:" => "crockett.gif",
  ":zorro:" => "zorro.gif",
  ":snap:" => "snap.gif",
  ":beer:" => "beer.gif",
  ":drunk:" => "drunk.gif",
  ":sleeping:" => "sleeping.gif",
  ":mama:" => "mama.gif",
  ":pepsi:" => "pepsi.gif",
  ":medieval:" => "medieval.gif",
  ":rambo:" => "rambo.gif",
  ":ninja:" => "ninja.gif",
  ":hannibal:" => "hannibal.gif",
  ":party:" => "party.gif",
  ":snorkle:" => "snorkle.gif",
  ":evo:" => "evo.gif",
  ":king:" => "king.gif",
  ":chef:" => "chef.gif",
  ":mario:" => "mario.gif",
  ":pope:" => "pope.gif",
  ":fez:" => "fez.gif",
  ":cap:" => "cap.gif",
  ":cowboy:" => "cowboy.gif",
  ":pirate:" => "pirate.gif",
  ":rock:" => "rock.gif",
  ":cigar:" => "cigar.gif",
  ":icecream:" => "icecream.gif",
  ":oldtimer:" => "oldtimer.gif",
  ":wolverine:" => "wolverine.gif",
  ":strongbench:" => "strongbench.gif",
  ":weakbench:" => "weakbench.gif",
  ":bike:" => "bike.gif",
  ":music:" => "music.gif",
  ":book:" => "book.gif",
  ":fish:" => "fish.gif",
  ":whistle:" => "whistle.gif",
  ":stupid:" => "stupid.gif",
  ":dots:" => "dots.gif",
  ":axe:" => "axe.gif",
  ":hooray:" => "hooray.gif",
  ":yay:" => "yay.gif",
  ":cake:" => "cake.gif",
  ":hbd:" => "hbd.gif",
  ":hi:" => "hi.gif",
  ":offtopic:" => "offtopic.gif",
  ":band:" => "band.gif",
  ":hump:" => "hump.gif",
  ":punk:" => "punk.gif",
  ":bounce:" => "bounce.gif",
  ":group:" => "group.gif",
  ":console:" => "console.gif",
  ":smurf:" => "smurf.gif",
  ":soldiers:" => "soldiers.gif",
  ":spidey:" => "spidey.gif",
  ":smurf:" => "smurf.gif",
  ":rant:" => "rant.gif",
  ":pimp:" => "pimp.gif",
  ":nuke:" => "nuke.gif",
  ":judge:" => "judge.gif",
  ":jacko:" => "jacko.gif",
  ":ike:" => "ike.gif",
  ":greedy:" => "greedy.gif",
  ":dumbells:" => "dumbells.gif",
  ":clover:" => "clover.gif",
  ":shit:" => "shit.gif",
);

$privatesmilies = array(
  ":-)" => "smile1.gif",
  ";-)" => "wink.gif",
  ":-D" => "grin.gif",
  ":-P" => "tongue.gif",
  ":-(" => "sad.gif",
  ":Boozer:" => "alcoholic.gif",
  ":deadhorse:" => "deadhorse.gif",
  ":spank:" => "spank.gif",
  ":yoji:" => "yoji.gif",
);

$tzs["-720"] = "(GMT - 12:00 hours) Enitwetok, Kwajalien";
$tzs["-660"] = "(GMT - 11:00 hours) Midway Island, Samoa";
$tzs["-600"] = "(GMT - 10:00 hours) Hawaii";
$tzs["-540"] = "(GMT - 9:00 hours) Alaska";
$tzs["-480"] = "(GMT - 8:00 hours) Pacific Time (US &amp; Canada)";
$tzs["-420"] = "(GMT - 7:00 hours) Mountain Time (US &amp; Canada)";
$tzs["-360"] = "(GMT - 6:00 hours) Central Time (US &amp; Canada), Mexico City";
$tzs["-300"] = "(GMT - 5:00 hours) Eastern Time (US &amp; Canada), Bogota, Lima, Quito";
$tzs["-240"] = "(GMT - 4:00 hours) Atlantic Time (Canada), Caracas, La Paz";
$tzs["-210"] = "(GMT - 3:30 hours) Newfoundland";
$tzs["-180"] = "(GMT - 3:00 hours) Brazil, Buenos Aires, Georgetown, Falkland Isl.";
$tzs["-120"] = "(GMT - 2:00 hours) Mid-Atlantic, Ascention Isl., St Helena";
$tzs["-60"]  = "(GMT - 1:00 hour) Azores, Cape Verde Islands";
$tzs["0"]    = "(GMT) Casablanca, Dublin, Edinburgh, London, Lisbon, Monrovia";
$tzs["60"]   = "(GMT + 1:00 hour) Amsterdam, Berlin, Copenhagen, Madrid, Paris, Rome";
$tzs["120"]  = "(GMT + 2:00 hours) Kaliningrad, South Africa, Warsaw";
$tzs["180"]  = "(GMT + 3:00 hours) Baghdad, Riyadh, Moscow, Nairobi";
$tzs["210"]  = "(GMT + 3:30 hours) Tehran";
$tzs["240"]  = "(GMT + 4:00 hours) Adu Dhabi, Baku, Muscat, Tbilisi";
$tzs["270"]  = "(GMT + 4:30 hours) Kabul";
$tzs["300"]  = "(GMT + 5:00 hours) Ekaterinburg, Islamabad, Karachi, Tashkent";
$tzs["330"]  = "(GMT + 5:30 hours) Bombay, Calcutta, Madras, New Delhi";
$tzs["360"]  = "(GMT + 6:00 hours) Almaty, Colomba, Dhakra";
$tzs["420"]  = "(GMT + 7:00 hours) Bangkok, Hanoi, Jakarta";
$tzs["480"]  = "(GMT + 8:00 hours) Beijing, Hong Kong, Perth, Singapore, Taipei";
$tzs["540"]  = "(GMT + 9:00 hours) Osaka, Sapporo, Seoul, Tokyo, Yakutsk";
$tzs["570"]  = "(GMT + 9:30 hours) Adelaide, Darwin";
$tzs["600"]  = "(GMT + 10:00 hours) Melbourne, Papua New Guinea, Sydney, Vladivostok";
$tzs["660"]  = "(GMT + 11:00 hours) Magadan, New Caledonia, Solomon Islands";
$tzs["720"]  = "(GMT + 12:00 hours) Auckland, Wellington, Fiji, Marshall Island";
?>